# Datadog Agent with Logs, APM, Processes, and System Probe enabled

targetSystem: "linux"
datadog:
  apiKey: <DATADOG_API_KEY>
  appKey: <DATADOG_APP_KEY>
  clusterName: <CLUSTER_NAME>
  tags: []
  env:
    # DD_KUBELET_TLS_VERIFY must be false on Azure Kubernetes Service (AKS)
    # - name: "DD_KUBELET_TLS_VERIFY"
    #   value: "false"
  logs:
    enabled: true
    containerCollectAll: false
    containerCollectUsingFiles: true
  apm:
    enabled: true
    socketPath: /var/run/datadog/apm.socket
    hostSocketPath: /var/run/datadog/
  processAgent:
    enabled: true
    processCollection: false
  systemProbe:
    enableTCPQueueLength: false
    enableOOMKill: true
    collectDNSStats: false
agents:
  enabled: true
  image:
    repository: gcr.io/datadoghq/agent
    tag: 7.23.1
    pullPolicy: IfNotPresent
